In [7]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split 
from sklearn import metrics
from sklearn.model_selection import cross_val_score


In [8]:
dta =sm.datasets.fair.load_pandas().data


In [9]:
dta.head()

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0            3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1            3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2            4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3            4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4            5.0  27.0          9.0       1.0        1.0  14.0         3.0   

   occupation_husb   affairs  
0              5.0  0.111111  
1              4.0  3.230769  
2              5.0  1.400000  
3              5.0  0.727273  
4              4.0  4.666666

In [11]:
dta.isnull().sum()

rate_marriage      0
age                0
yrs_married        0
children           0
religious          0
educ               0
occupation         0
occupation_husb    0
affairs            0
dtype: int64

In [12]:
dta.describe()

rate_marriage          age  yrs_married     children    religious  \
count    6366.000000  6366.000000  6366.000000  6366.000000  6366.000000   
mean        4.109645    29.082862     9.009425     1.396874     2.426170   
std         0.961430     6.847882     7.280120     1.433471     0.878369   
min         1.000000    17.500000     0.500000     0.000000     1.000000   
25%         4.000000    22.000000     2.500000     0.000000     2.000000   
50%         4.000000    27.000000     6.000000     1.000000     2.000000   
75%         5.000000    32.000000    16.500000     2.000000     3.000000   
max         5.000000    42.000000    23.000000     5.500000     4.000000   

              educ   occupation  occupation_husb      affairs  
count  6366.000000  6366.000000      6366.000000  6366.000000  
mean     14.209865     3.424128         3.850141     0.705374  
std       2.178003     0.942399         1.346435     2.203374  
min       9.000000     1.000000         1.000000     0.000000  
25%      12.000000     3.000000         3.000000     0.000000  
50%      14.000000     3.000000         4.000000     0.000000  
75%      16.000000     4.000000         5.000000     0.484848  
max      20.000000     6.000000         6.000000    57.599991

In [13]:
dta['affair'] = (dta.affairs>0).astype(int)


In [15]:
dta

rate_marriage   age  yrs_married  children  religious  educ  occupation  \
0               3.0  32.0          9.0       3.0        3.0  17.0         2.0   
1               3.0  27.0         13.0       3.0        1.0  14.0         3.0   
2               4.0  22.0          2.5       0.0        1.0  16.0         3.0   
3               4.0  37.0         16.5       4.0        3.0  16.0         5.0   
4               5.0  27.0          9.0       1.0        1.0  14.0         3.0   
...             ...   ...          ...       ...        ...   ...         ...   
6361            5.0  32.0         13.0       2.0        3.0  17.0         4.0   
6362            4.0  32.0         13.0       1.0        1.0  16.0         5.0   
6363            5.0  22.0          2.5       0.0        2.0  14.0         3.0   
6364            5.0  32.0          6.0       1.0        3.0  14.0         3.0   
6365            4.0  22.0          2.5       0.0        2.0  16.0         2.0   

      occupation_husb   affairs  affair  
0                 5.0  0.111111       1  
1                 4.0  3.230769       1  
2                 5.0  1.400000       1  
3                 5.0  0.727273       1  
4                 4.0  4.666666       1  
...               ...       ...     ...  
6361              3.0  0.000000       0  
6362              5.0  0.000000       0  
6363              1.0  0.000000       0  
6364              4.0  0.000000       0  
6365              4.0  0.000000       0  

[6366 rows x 10 columns]

In [21]:
y, X = dmatrices('affair ~ rate_marriage + age +yrs_married + children +religious + educ +C(occupation) + C(occupation_husb)',dta, return_type="dataframe")
   

In [23]:
X.columns

Index(['Intercept', 'C(occupation)[T.2.0]', 'C(occupation)[T.3.0]',
       'C(occupation)[T.4.0]', 'C(occupation)[T.5.0]', 'C(occupation)[T.6.0]',
       'C(occupation_husb)[T.2.0]', 'C(occupation_husb)[T.3.0]',
       'C(occupation_husb)[T.4.0]', 'C(occupation_husb)[T.5.0]',
       'C(occupation_husb)[T.6.0]', 'rate_marriage', 'age', 'yrs_married',
       'children', 'religious', 'educ'],
      dtype='object')

In [24]:
X = X.rename(columns =
    {'C(occupation)[T.2.0]':'occ_2',

    'C(occupation)[T.3.0]':'occ_3',
    'C(occupation)[T.4.0]':'occ_4',
    'C(occupation)[T.5.0]':'occ_5',
    'C(occupation)[T.6.0]':'occ_6',
    'C(occupation_husb)[T.2.0]':'occ_husb_2',
    'C(occupation_husb)[T.3.0]':'occ_husb_3',
    'C(occupation_husb)[T.4.0]':'occ_husb_4',
    'C(occupation_husb)[T.5.0]':'occ_husb_5',
    'C(occupation_husb)[T.6.0]':'occ_husb_6'})



In [25]:
X.columns

Index(['Intercept', 'occ_2', 'occ_3', 'occ_4', 'occ_5', 'occ_6', 'occ_husb_2',
       'occ_husb_3', 'occ_husb_4', 'occ_husb_5', 'occ_husb_6', 'rate_marriage',
       'age', 'yrs_married', 'children', 'religious', 'educ'],
      dtype='object')

In [27]:
X

Intercept  occ_2  occ_3  occ_4  occ_5  occ_6  occ_husb_2  occ_husb_3  \
0           1.0    1.0    0.0    0.0    0.0    0.0         0.0         0.0   
1           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
2           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
3           1.0    0.0    0.0    0.0    1.0    0.0         0.0         0.0   
4           1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
...         ...    ...    ...    ...    ...    ...         ...         ...   
6361        1.0    0.0    0.0    1.0    0.0    0.0         0.0         1.0   
6362        1.0    0.0    0.0    0.0    1.0    0.0         0.0         0.0   
6363        1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
6364        1.0    0.0    1.0    0.0    0.0    0.0         0.0         0.0   
6365        1.0    1.0    0.0    0.0    0.0    0.0         0.0         0.0   

      occ_husb_4  occ_husb_5  occ_husb_6  rate_marriage   age  yrs_married  \
0            0.0         1.0         0.0            3.0  32.0          9.0   
1            1.0         0.0         0.0            3.0  27.0         13.0   
2            0.0         1.0         0.0            4.0  22.0          2.5   
3            0.0         1.0         0.0            4.0  37.0         16.5   
4            1.0         0.0         0.0            5.0  27.0          9.0   
...          ...         ...         ...            ...   ...          ...   
6361         0.0         0.0         0.0            5.0  32.0         13.0   
6362         0.0         1.0         0.0            4.0  32.0         13.0   
6363         0.0         0.0         0.0            5.0  22.0          2.5   
6364         1.0         0.0         0.0            5.0  32.0          6.0   
6365         1.0         0.0         0.0            4.0  22.0          2.5   

      children  religious  educ  
0          3.0        3.0  17.0  
1          3.0        1.0  14.0  
2          0.0        1.0  16.0  
3          4.0        3.0  16.0  
4          1.0        1.0  14.0  
...        ...        ...   ...  
6361       2.0        3.0  17.0  
6362       1.0        1.0  16.0  
6363       0.0        2.0  14.0  
6364       1.0        3.0  14.0  
6365       0.0        2.0  16.0  

[6366 rows x 17 columns]

In [29]:
y=np.ravel(y)

In [30]:
y

array([1., 1., 1., ..., 0., 0., 0.])

In [32]:
lr_model = LogisticRegression()

In [34]:
lr_model.fit(X,y)

C:\Users\DHOLE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [35]:
lr_model.score(X,y)

0.7258875274897895

In [36]:
x_train,x_test,y_train,y_test = train_test_split(X,y,random_state=30,test_size=0.3)
#X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 100, test_size=0.3)

In [37]:
lr_model1 = LogisticRegression()

In [38]:
lr_model1.fit(x_train,y_train)

C:\Users\DHOLE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [39]:
lr_model1.score(x_test,y_test)

0.7335078534031414

In [42]:
prediction = lr_model1.predict(x_test)
prediction

array([0., 1., 1., ..., 0., 1., 0.])

In [44]:
scores = cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=10)
scores

C:\Users\DHOLE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\DHOLE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.72370487, 0.69544741, 0.73940345, 0.70957614, 0.71428571,
       0.72841444, 0.72641509, 0.70283019, 0.75314465, 0.75157233])

In [46]:
from sklearn.metrics import roc_auc_score
print(f'Roc Auc Score : {roc_auc_score(y_test,prediction)}')

Roc Auc Score : 0.6241983131064207
