In [70]:
import numpy as np
def f2(ar,n,increasing=False):
    if increasing:
        m = np.matrix([x**i for x in ar for i in range(n)]).reshape(ar.size,n)
        return m
    else:
        m = np.matrix([x**(n-i-1) for x in ar for i in range(n)]).reshape(ar.size,n)
    return m

In [77]:
f =np.array([1,2,3])
ab = f2(f,4)
print(ab)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]


In [79]:
bc = f2(f,4,True)
print(bc)

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]]


In [ ]:
Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [82]:
abc = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window = 3

In [95]:
def movavg(ar,j):
    z=1
    mavg = np.convolve(ar,np.ones(j),'valid')/j
    for i in mavg:
        print("y{0} = {1:.2f}".format(z,i))
        z+=1
    
movavg(abc,3)

y1 = 5.00
y2 = 4.67
y3 = 5.67
y4 = 6.67
y5 = 9.67
y6 = 28.67
y7 = 49.33
y8 = 72.67
y9 = 84.00
y10 = 93.33
y11 = 116.33
